url = "https://download.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2"
variant = "fedora43"
name = "Fedora 43"
description = ""
cloudinit_templates = ["meta-data.template", "user-data.template"]
